"""Shared LLM orchestration for the travel assistant."""

from __future__ import annotations

from typing import Any, AsyncGenerator, Dict, Iterable, List, Literal, Sequence

from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage
from loguru import logger
from pydantic import BaseModel, Field

from app.config import config
from app.core.llm_factory import llm_factory
from app.models.travel import IntentRouteResult, TripContextMemory, UserProfileMemory
from app.skills import skill_registry
from app.services.travel_utils import chunk_text


class ExecutionStep(BaseModel):
    """Structured execution step for plan-and-execute."""

    title: str = Field(description="Step title")
    action: str = Field(description="Concrete action to take")
    rationale: str = Field(description="Why this action matters")


class ReplanArtifact(BaseModel):
    """Structured re-planning artifact generated by the LLM."""

    conflict_type: str = Field(description="Conflict category")
    objective: str = Field(description="What the updated plan should optimize for")
    must_keep: List[str] = Field(default_factory=list, description="Items that should be kept")
    candidate_options: List[str] = Field(
        default_factory=list, description="Possible candidate adjustment options"
    )
    recommended_option: str = Field(description="Recommended option summary")
    execution_steps: List[ExecutionStep] = Field(
        default_factory=list, description="Recommended execution steps"
    )
    risks: List[str] = Field(default_factory=list, description="Risks or caveats")


class MultiAgentTask(BaseModel):
    """Lead-planner task assigned to a specialist role."""

    role_name: Literal[
        "Destination Researcher",
        "Transport And Stay Analyst",
        "Itinerary Designer",
        "Risk Advisor",
    ]
    objective: str = Field(description="Task objective for the assigned role")
    destinations: List[str] = Field(default_factory=list, description="Relevant destinations")
    success_criteria: List[str] = Field(
        default_factory=list, description="How the role knows the task is complete"
    )


class LeadPlannerPlan(BaseModel):
    """Structured task decomposition for multi-agent deep search."""

    overall_goal: str = Field(description="Overall goal for the lead planner")
    decision_criteria: List[str] = Field(
        default_factory=list, description="How the final recommendation should be judged"
    )
    tasks: List[MultiAgentTask] = Field(default_factory=list, description="Specialist tasks")
    synthesis_instruction: str = Field(description="How the lead planner should synthesize outputs")


class ReActDecision(BaseModel):
    """Single ReAct step for a specialist sub-agent."""

    thought: str = Field(description="Short reasoning summary for the next step")
    action: Literal[
        "read_shared_context",
        "retrieve_knowledge",
        "plan_destination",
        "replan_trip",
        "search_web_live",
        "scrape_web_page",
        "inspect_peer_findings",
        "finish",
    ]
    action_input: str = Field(default="", description="Input for the chosen action")
    finish_answer: str = Field(default="", description="Final answer when action is finish")


class TravelLLMService:
    """Thin wrapper around the configured chat model."""

    def is_available(self) -> bool:
        return bool(config.dashscope_api_key)

    def _create_model(self, *, streaming: bool, temperature: float = 0.45):
        return llm_factory.create_chat_model(
            model=config.dashscope_model,
            temperature=temperature,
            streaming=streaming,
        )

    @staticmethod
    def _get_available_tools(*, live_only: bool = False) -> List[Any]:
        blocked = {"summarize_preference_memory"}
        live_only_names = {"search_web_live", "scrape_web_page"}
        tools: List[Any] = []
        for tool in skill_registry.get_all_tools():
            tool_name = getattr(tool, "name", "")
            if tool_name in blocked:
                continue
            if live_only and tool_name not in live_only_names:
                continue
            tools.append(tool)
        return tools

    @staticmethod
    def _requires_live_tools(question: str) -> bool:
        normalized = question.lower()
        live_markers = [
            "最新",
            "最近",
            "实时",
            "当前",
            "今日",
            "今天",
            "weather",
            "visa",
            "汇率",
            "营业时间",
            "opening hours",
            "price",
            "票价",
            "政策",
        ]
        return any(marker in normalized for marker in live_markers)

    async def _invoke_text_with_tools(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.45,
        max_tool_rounds: int = 4,
        live_only: bool = False,
    ) -> tuple[str, Dict[str, Any]]:
        model = self._create_model(streaming=False, temperature=temperature)
        tools = self._get_available_tools(live_only=live_only)
        metadata: Dict[str, Any] = {
            "tool_enabled": bool(tools),
            "tool_used": False,
            "tool_calls": [],
        }

        if not tools:
            response = await model.ainvoke(
                [SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)]
            )
            return self._coerce_text(getattr(response, "content", response)).strip(), metadata

        bind_kwargs: Dict[str, Any] = {}
        if live_only:
            bind_kwargs["tool_choice"] = "required"
        llm_with_tools = model.bind_tools(tools, **bind_kwargs)
        tool_map = {
            getattr(tool, "name", f"tool_{index}"): tool
            for index, tool in enumerate(tools)
        }
        messages: List[Any] = [
            SystemMessage(content=system_prompt),
            HumanMessage(content=user_prompt),
        ]

        for _ in range(max_tool_rounds):
            response = await llm_with_tools.ainvoke(messages)
            messages.append(response)

            tool_calls = getattr(response, "tool_calls", None) or []
            if tool_calls:
                metadata["tool_used"] = True
                metadata["tool_calls"].extend(
                    [call.get("name", "unknown") for call in tool_calls if isinstance(call, dict)]
                )
                for call in tool_calls:
                    if not isinstance(call, dict):
                        continue
                    tool_name = call.get("name", "unknown")
                    tool_args = call.get("args", {}) or {}
                    tool_call_id = call.get("id", tool_name)
                    tool_obj = tool_map.get(tool_name)
                    if tool_obj is None:
                        tool_content = f"Tool '{tool_name}' is not available."
                    else:
                        try:
                            if hasattr(tool_obj, "ainvoke"):
                                tool_result = await tool_obj.ainvoke(tool_args)
                            else:
                                tool_result = tool_obj.invoke(tool_args)
                            tool_content = self._coerce_text(tool_result) or str(tool_result)
                        except Exception as exc:
                            logger.warning(f"Tool call failed for {tool_name}: {exc}")
                            tool_content = f"Tool '{tool_name}' failed: {exc}"
                    messages.append(ToolMessage(content=tool_content, tool_call_id=tool_call_id))
                continue

            answer = self._coerce_text(getattr(response, "content", response)).strip()
            return answer, metadata

        fallback = ""
        for message in reversed(messages):
            text = self._coerce_text(getattr(message, "content", message)).strip()
            if text:
                fallback = text
                break
        return fallback, metadata

    async def generate_final_answer(
        self,
        *,
        question: str,
        route: IntentRouteResult,
        user_profile: UserProfileMemory,
        trip_context: TripContextMemory,
        session_history: Sequence[Dict[str, Any]],
        draft: str,
        knowledge_context: str = "",
        metadata: Dict[str, Any] | None = None,
    ) -> tuple[str, Dict[str, Any]]:
        metadata = dict(metadata or {})
        metadata.setdefault("llm_enabled", self.is_available())

        if not self.is_available():
            metadata["llm_used"] = False
            metadata["generation_mode"] = "template_fallback"
            return draft, metadata

        try:
            live_only = self._requires_live_tools(question)
            answer, tool_metadata = await self._invoke_text_with_tools(
                system_prompt=self._build_system_prompt(route),
                user_prompt=self._build_user_prompt(
                    question=question,
                    route=route,
                    user_profile=user_profile,
                    trip_context=trip_context,
                    session_history=session_history,
                    draft=draft,
                    knowledge_context=knowledge_context,
                    metadata=metadata,
                ),
                live_only=live_only,
            )
            if not answer.strip():
                raise ValueError("Model returned empty content")

            answer = self._compose_user_answer(route=route, llm_overlay=answer, draft=draft)
            metadata.update(tool_metadata)
            metadata["live_tool_hint"] = live_only
            metadata["llm_used"] = True
            metadata["generation_mode"] = (
                "llm_with_tools" if tool_metadata.get("tool_used") else "llm"
            )
            return answer, metadata
        except Exception as exc:
            logger.warning(f"Travel LLM final answer generation failed, using fallback: {exc}")
            metadata["llm_used"] = False
            metadata["generation_mode"] = "template_fallback"
            metadata["fallback_reason"] = str(exc)
            return draft, metadata

    async def stream_final_answer(
        self,
        *,
        question: str,
        route: IntentRouteResult,
        user_profile: UserProfileMemory,
        trip_context: TripContextMemory,
        session_history: Sequence[Dict[str, Any]],
        draft: str,
        knowledge_context: str = "",
        metadata: Dict[str, Any] | None = None,
    ) -> AsyncGenerator[str, None]:
        answer, _ = await self.generate_final_answer(
            question=question,
            route=route,
            user_profile=user_profile,
            trip_context=trip_context,
            session_history=session_history,
            draft=draft,
            knowledge_context=knowledge_context,
            metadata=metadata,
        )
        for chunk in chunk_text(answer):
            yield chunk

    async def generate_role_output(
        self,
        *,
        role_name: str,
        role_goal: str,
        question: str,
        user_profile: UserProfileMemory,
        trip_context: TripContextMemory,
        shared_context: str,
    ) -> str:
        if not self.is_available():
            return ""

        try:
            model = self._create_model(streaming=False, temperature=0.35)
            response = await model.ainvoke(
                [
                    SystemMessage(
                        content=(
                            f"You are the {role_name} in a travel-agent system. "
                            f"Your goal is: {role_goal}. "
                            "Write in Chinese. Be concrete, practical, and brief. "
                            "Do not repeat the whole user request."
                        )
                    ),
                    HumanMessage(
                        content=(
                            f"User question:\n{question}\n\n"
                            f"User profile:\n{self._format_user_profile(user_profile)}\n\n"
                            f"Trip context:\n{self._format_trip_context(trip_context)}\n\n"
                            f"Shared context:\n{shared_context}\n\n"
                            "Please return 3 to 5 bullet points and one short concluding sentence."
                        )
                    ),
                ]
            )
            return self._coerce_text(getattr(response, "content", response)).strip()
        except Exception as exc:
            logger.warning(f"Role generation failed for {role_name}: {exc}")
            return ""

    async def generate_replan_artifact(
        self,
        *,
        question: str,
        user_profile: UserProfileMemory,
        trip_context: TripContextMemory,
        deterministic_brief: str,
    ) -> ReplanArtifact | None:
        if not self.is_available():
            return None

        try:
            model = self._create_model(streaming=False, temperature=0.25)
            structured_model = model.with_structured_output(ReplanArtifact)
            artifact = await structured_model.ainvoke(
                [
                    SystemMessage(
                        content=(
                            "You are a travel plan-and-execute coordinator. "
                            "Extract the travel disruption, preserve key constraints, "
                            "and produce a structured replan artifact."
                        )
                    ),
                    HumanMessage(
                        content=(
                            f"User question:\n{question}\n\n"
                            f"User profile:\n{self._format_user_profile(user_profile)}\n\n"
                            f"Trip context:\n{self._format_trip_context(trip_context)}\n\n"
                            f"Deterministic brief:\n{deterministic_brief}\n\n"
                            "Return a complete artifact. Candidate options should be concise."
                        )
                    ),
                ]
            )
            return artifact
        except Exception as exc:
            logger.warning(f"Structured replan artifact generation failed: {exc}")
            return None

    async def plan_multi_agent_tasks(
        self,
        *,
        question: str,
        user_profile: UserProfileMemory,
        trip_context: TripContextMemory,
        shared_context: str,
        completed_findings: str = "",
        pending_updates: Sequence[str] | None = None,
    ) -> LeadPlannerPlan | None:
        if not self.is_available():
            return None

        try:
            model = self._create_model(streaming=False, temperature=0.2)
            structured_model = model.with_structured_output(LeadPlannerPlan)
            return await structured_model.ainvoke(
                [
                    SystemMessage(
                        content=(
                            "你是 TripBuddy 的 Lead Planner。"
                            "你的任务是收到用户问题后，把任务分解给不同的旅行专家角色。"
                            "只能使用这些角色：Destination Researcher、Transport And Stay Analyst、"
                            "Itinerary Designer、Risk Advisor。"
                            "请做最小但完整的任务分解，通常输出 3 到 4 个 task。"
                            "如果有人类追加条件，要把它视为高优先级约束，反映到后续任务中。"
                        )
                    ),
                    HumanMessage(
                        content=(
                            f"用户问题：\n{question}\n\n"
                            f"用户画像：\n{self._format_user_profile(user_profile)}\n\n"
                            f"Trip context：\n{self._format_trip_context(trip_context)}\n\n"
                            f"共享上下文：\n{shared_context[:2200]}\n\n"
                            f"已完成发现：\n{completed_findings or '暂无'}\n\n"
                            f"用户追加条件：\n{chr(10).join(pending_updates or []) or '暂无'}\n\n"
                            "请返回结构化任务分解。每个 task 要明确 objective、destinations 和 success_criteria。"
                        )
                    ),
                ]
            )
        except Exception as exc:
            logger.warning(f"Lead planner task decomposition failed: {exc}")
            return None

    async def decide_react_step(
        self,
        *,
        role_name: str,
        role_goal: str,
        task_objective: str,
        question: str,
        user_profile: UserProfileMemory,
        trip_context: TripContextMemory,
        shared_context: str,
        peer_findings: str,
        scratchpad: str,
        pending_updates: Sequence[str] | None = None,
    ) -> ReActDecision | None:
        if not self.is_available():
            return None

        try:
            model = self._create_model(streaming=False, temperature=0.2)
            structured_model = model.with_structured_output(ReActDecision)
            return await structured_model.ainvoke(
                [
                    SystemMessage(
                        content=(
                            f"你是 TripBuddy 的子 Agent：{role_name}。"
                            f"你的职责是：{role_goal}。"
                            "你要用 ReAct 方式工作：先判断下一步，再选择一个 action。"
                            "可选 action 只有：read_shared_context、retrieve_knowledge、plan_destination、"
                            "replan_trip、inspect_peer_findings、finish。"
                            "如果已有足够信息，就输出 finish。"
                            "整个过程追求收敛，避免重复读取同一个信息源。"
                        )
                    ),
                    HumanMessage(
                        content=(
                            f"用户问题：\n{question}\n\n"
                            f"当前任务目标：\n{task_objective}\n\n"
                            f"用户画像：\n{self._format_user_profile(user_profile)}\n\n"
                            f"Trip context：\n{self._format_trip_context(trip_context)}\n\n"
                            f"共享上下文：\n{shared_context[:1800]}\n\n"
                            f"其他角色已完成发现：\n{peer_findings or '暂无'}\n\n"
                            f"当前 scratchpad：\n{scratchpad or '暂无'}\n\n"
                            f"用户最新追加条件：\n{chr(10).join(pending_updates or []) or '暂无'}\n\n"
                            "请输出下一步 ReAct 决策。finish_answer 只在 finish 时填写。"
                        )
                    ),
                ]
            )
        except Exception as exc:
            logger.warning(f"ReAct decision failed for {role_name}: {exc}")
            return None

    def _build_system_prompt(self, route: IntentRouteResult) -> str:
        common_rules = (
            "你是 TripBuddy，一个旅行规划与重规划助手。"
            "必须使用中文回答。"
            "你会收到结构化执行草稿、用户记忆、trip context 和可选的知识库内容。"
            "这些内容都是已知事实，你必须优先使用。"
            "如果上下文里已经出现目的地、天数、预算、偏好、同行人，你绝对不能说“用户没有提供”。"
            "你的主要任务不是重写整份草稿，而是基于草稿补一段更自然的总结、推荐理由和下一步建议。"
            "不要擅自替换目的地，也不要把具体草稿改写成泛泛模板。"
            "如果知识上下文提示没有实时天气、汇率、签证接口，要保留这种诚实说明。"
            "禁止编造实时库存、票价、天气、签证政策、营业时间。"
        )

        if route.route_type == "knowledge":
            return (
                common_rules
                + "当前任务偏向旅行问答与攻略建议，请给出清晰、直接、实用的回答。"
            )
        if route.route_type == "workflow":
            return (
                common_rules
                + "当前任务偏向固定 workflow，请把草稿加工成高质量成品，例如行程、推荐、清单或预算拆分。"
            )
        if route.route_type == "multi_agent":
            return (
                common_rules
                + "当前任务偏向多角色协作，请你作为 Lead Planner 汇总角色结论，并明确说明取舍。"
            )
        return (
            common_rules
            + "当前任务偏向 plan-and-execute 重规划，请优先保留 must-do 项目并最小化改动成本。"
        )

    async def decide_react_step(
        self,
        *,
        role_name: str,
        role_goal: str,
        task_objective: str,
        question: str,
        user_profile: UserProfileMemory,
        trip_context: TripContextMemory,
        shared_context: str,
        peer_findings: str,
        scratchpad: str,
        pending_updates: Sequence[str] | None = None,
    ) -> ReActDecision | None:
        if not self.is_available():
            return None

        try:
            model = self._create_model(streaming=False, temperature=0.2)
            structured_model = model.with_structured_output(ReActDecision)
            return await structured_model.ainvoke(
                [
                    SystemMessage(
                        content=(
                            f"You are the TripBuddy specialist sub-agent: {role_name}. "
                            f"Your responsibility is: {role_goal}. "
                            "Use a compact ReAct decision policy. "
                            "Choose exactly one next action from: "
                            "read_shared_context, retrieve_knowledge, plan_destination, "
                            "replan_trip, search_web_live, scrape_web_page, inspect_peer_findings, finish. "
                            "Use search_web_live when the task depends on current web information. "
                            "Use scrape_web_page only after you already have a useful URL or domain hint. "
                            "Finish as soon as you have enough evidence. Avoid repeating the same lookup."
                        )
                    ),
                    HumanMessage(
                        content=(
                            f"User question:\n{question}\n\n"
                            f"Current task objective:\n{task_objective}\n\n"
                            f"User profile:\n{self._format_user_profile(user_profile)}\n\n"
                            f"Trip context:\n{self._format_trip_context(trip_context)}\n\n"
                            f"Shared context:\n{shared_context[:1800]}\n\n"
                            f"Peer findings:\n{peer_findings or 'none'}\n\n"
                            f"Scratchpad:\n{scratchpad or 'none'}\n\n"
                            f"Human updates:\n{chr(10).join(pending_updates or []) or 'none'}\n\n"
                            "Return one structured ReActDecision. Fill finish_answer only when action=finish."
                        )
                    ),
                ]
            )
        except Exception as exc:
            logger.warning(f"ReAct decision failed for {role_name}: {exc}")
            return None

    def _build_system_prompt(self, route: IntentRouteResult) -> str:
        common_rules = (
            "You are TripBuddy, a travel planning and re-planning assistant. "
            "Always answer in Chinese. "
            "You receive structured facts, memory, trip context, a draft, and optional knowledge snippets. "
            "Treat those inputs as trusted facts and do not contradict them. "
            "If destination, days, budget, preferences, or companions already appear in context, never claim the user did not provide them. "
            "Your job is to improve, summarize, and finalize the draft instead of replacing it with an unrelated plan. "
            "Do not invent live weather, exchange rates, visa policy, opening hours, prices, or availability. "
            "When the request depends on current web information, use the available tools such as search_web_live and scrape_web_page before answering. "
            "If tool outputs contain useful URLs, keep the most important source links in the answer."
        )

        if route.route_type == "knowledge":
            return common_rules + " Focus on concise travel Q&A and practical recommendations."
        if route.route_type == "workflow":
            return common_rules + " Focus on polishing the workflow draft into a user-ready answer."
        if route.route_type == "multi_agent":
            return common_rules + " Act as the Lead Planner and synthesize specialist findings with clear trade-offs."
        return common_rules + " Focus on plan-and-execute style re-planning with minimal disruption."

    def _build_user_prompt(
        self,
        *,
        question: str,
        route: IntentRouteResult,
        user_profile: UserProfileMemory,
        trip_context: TripContextMemory,
        session_history: Sequence[Dict[str, Any]],
        draft: str,
        knowledge_context: str,
        metadata: Dict[str, Any],
    ) -> str:
        fact_block = self._format_fact_block(route, user_profile, trip_context)
        history_block = self._format_history(session_history)
        metadata_block = "\n".join(
            f"- {key}: {value}" for key, value in metadata.items() if key != "fallback_reason"
        )

        if route.route_type == "workflow":
            sections = [
                "任务：基于下面的旅行 workflow 草稿，生成一段简短的个性化总结。",
                f"用户问题：{question}",
                f"不可变事实：\n{fact_block}",
                "硬约束：\n"
                "- 绝对不能更换目的地、天数、预算、偏好。\n"
                "- 绝对不能说“用户没有提供信息”，因为已知事实都写在上面。\n"
                "- 不要重写 Day 1 / Day 2 等草稿主体。\n"
                "- 只负责生成“这份方案为什么适合用户”的总结和一个自然下一步。",
                f"结构化执行草稿：\n{draft}",
            ]
            if knowledge_context:
                sections.append(f"可参考的知识库补充：\n{knowledge_context}")
            sections.append(
                "请只输出两部分：\n"
                "1. 2 到 4 句个性化总结。\n"
                "2. 1 句自然的下一步建议。\n"
                "不要重复整份草稿，不要自造新的完整行程。"
            )
            return "\n\n".join(sections)

        if route.route_type == "multi_agent":
            sections = [
                "任务：你是 Lead Planner，请基于下面的多角色分析生成一段最终推荐总结。",
                f"用户问题：{question}",
                f"不可变事实：\n{fact_block}",
                "硬约束：\n"
                "- 必须围绕草稿里已经比较的目的地和约束来写。\n"
                "- 要明确说明推荐结论、取舍理由，以及谁更适合哪种用户。\n"
                "- 不要重写下面的整份角色草稿。",
                f"多角色分析草稿：\n{draft}",
            ]
            if knowledge_context:
                sections.append(f"补充知识：\n{knowledge_context}")
            sections.append(
                "请只输出两部分：\n"
                "1. 4 到 6 条最终推荐总结。\n"
                "2. 1 句自然的下一步建议。"
            )
            return "\n\n".join(sections)

        if route.route_type == "plan_execute":
            sections = [
                "任务：请基于下面的 plan-and-execute 草稿，写一段最终执行摘要。",
                f"用户问题：{question}",
                f"不可变事实：\n{fact_block}",
                "硬约束：\n"
                "- 必须保留冲突类型、推荐方案、执行步骤的核心内容。\n"
                "- 优先保留 must-do 项和已知约束，不能随意改目的地或场景。\n"
                "- 不要重写下面的完整步骤草稿。",
                f"重规划草稿：\n{draft}",
            ]
            if knowledge_context:
                sections.append(f"补充知识：\n{knowledge_context}")
            sections.append(
                "请只输出两部分：\n"
                "1. 2 到 4 条执行摘要，告诉用户核心该怎么改。\n"
                "2. 1 句自然的下一步建议。"
            )
            return "\n\n".join(sections)

        sections = [
            "任务：请基于用户问题、已知事实、知识库和草稿生成一段简洁总结。",
            f"用户问题：{question}",
            f"不可变事实：\n{fact_block}",
            "硬约束：\n"
            "- 如果知识库和草稿已经能回答问题，就不要泛泛而谈。\n"
            "- 如果涉及实时天气、汇率、签证，而上下文没有可靠实时数据，要明确说明限制。\n"
            "- 不要重写整份草稿。",
            f"最近对话历史：\n{history_block}",
            f"问答草稿：\n{draft}",
        ]
        if knowledge_context:
            sections.append(f"知识库上下文：\n{knowledge_context}")
        if metadata_block:
            sections.append(f"执行元数据：\n{metadata_block}")
        sections.append(
            "请只输出两部分：\n"
            "1. 2 到 5 条简洁总结或提醒。\n"
            "2. 1 句自然的下一步建议。"
        )
        return "\n\n".join(sections)

    @staticmethod
    def _format_user_profile(user_profile: UserProfileMemory) -> str:
        lines = [
            f"budget_preference={user_profile.budget_preference or 'unknown'}",
            f"travel_style={', '.join(user_profile.travel_style) or 'unknown'}",
            f"dietary_preferences={', '.join(user_profile.dietary_preferences) or 'unknown'}",
            f"pace_preference={user_profile.pace_preference or 'unknown'}",
            f"accommodation_preference={user_profile.accommodation_preference or 'unknown'}",
            f"companion_preference={', '.join(user_profile.companion_preference) or 'unknown'}",
            f"preferred_destinations={', '.join(user_profile.preferred_destinations) or 'unknown'}",
            f"notes={', '.join(user_profile.notes) or 'none'}",
        ]
        return "\n".join(lines)

    @staticmethod
    def _format_trip_context(trip_context: TripContextMemory) -> str:
        lines = [
            f"origin={trip_context.origin or 'unknown'}",
            f"destination={trip_context.destination or 'unknown'}",
            f"travel_month={trip_context.travel_month or 'unknown'}",
            f"duration_days={trip_context.duration_days or 'unknown'}",
            f"budget_amount={trip_context.budget_amount or 'unknown'}",
            f"companions={', '.join(trip_context.companions) or 'unknown'}",
            f"interests={', '.join(trip_context.interests) or 'unknown'}",
            f"must_do={', '.join(trip_context.must_do) or 'none'}",
            f"constraints={', '.join(trip_context.constraints) or 'none'}",
            f"open_questions={', '.join(trip_context.open_questions) or 'none'}",
            f"current_plan={(trip_context.current_plan or 'none')[:1000]}",
        ]
        return "\n".join(lines)

    @staticmethod
    def _format_fact_block(
        route: IntentRouteResult,
        user_profile: UserProfileMemory,
        trip_context: TripContextMemory,
    ) -> str:
        lines = [
            f"- 路由意图: {route.intent}",
            f"- 执行模式: {route.route_type}",
            f"- workflow: {route.selected_workflow or '无'}",
            f"- 目的地: {trip_context.destination or '未提及'}",
            f"- 出发地: {trip_context.origin or '未提及'}",
            f"- 天数: {trip_context.duration_days or '未提及'}",
            f"- 预算: {trip_context.budget_amount or '未提及'}",
            f"- 同行人: {'、'.join(trip_context.companions) or '未提及'}",
            f"- 兴趣: {'、'.join(trip_context.interests) or '未提及'}",
            f"- 节奏偏好: {user_profile.pace_preference or '未提及'}",
            f"- 住宿偏好: {user_profile.accommodation_preference or '未提及'}",
            f"- 饮食偏好: {'、'.join(user_profile.dietary_preferences) or '未提及'}",
        ]
        return "\n".join(lines)

    @staticmethod
    def _compose_user_answer(*, route: IntentRouteResult, llm_overlay: str, draft: str) -> str:
        overlay = llm_overlay.strip()
        base = draft.strip()

        if route.route_type == "knowledge":
            return f"{overlay}\n\n{base}".strip() if overlay else base
        if route.route_type == "workflow":
            return f"{overlay}\n\n{base}".strip() if overlay else base
        if route.route_type == "multi_agent":
            return f"{overlay}\n\n{base}".strip() if overlay else base
        return f"{overlay}\n\n{base}".strip() if overlay else base

    @staticmethod
    def _format_history(session_history: Sequence[Dict[str, Any]], *, limit: int = 6) -> str:
        if not session_history:
            return "No previous turns."

        items: List[str] = []
        for entry in session_history[-limit:]:
            role = entry.get("role", "unknown")
            content = str(entry.get("content", "")).strip().replace("\n", " ")
            items.append(f"{role}: {content[:240]}")
        return "\n".join(items)

    @classmethod
    def _coerce_text(cls, content: Any) -> str:
        if content is None:
            return ""
        if isinstance(content, str):
            return content
        if isinstance(content, list):
            return "".join(cls._coerce_text(item) for item in content)
        if isinstance(content, dict):
            if "text" in content:
                return cls._coerce_text(content["text"])
            if "content" in content:
                return cls._coerce_text(content["content"])
            if "output_text" in content:
                return cls._coerce_text(content["output_text"])
            return ""
        text_attr = getattr(content, "text", None)
        if text_attr is not None:
            return cls._coerce_text(text_attr)
        content_attr = getattr(content, "content", None)
        if content_attr is not None and content_attr is not content:
            return cls._coerce_text(content_attr)
        if isinstance(content, Iterable) and not isinstance(content, (bytes, bytearray)):
            return "".join(cls._coerce_text(item) for item in content)
        return str(content)


travel_llm_service = TravelLLMService()
